name: on-commit

on:
  push:
    branches:
      - develop
      - feat/ci-notify

jobs:
  python-version:
    name: example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Running builder.py
        run: python ./src/builder.py
      - name: Running bot.py
        run: python ./chore/bot.py
