name: on-pull-request

on:
  pull_request:
    branches:
      - develop
      - feat/ci-builder

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: print python version
        run: python --version
      - name: Running builder.py
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: python ./src/builder.py
