name: scheduler
on:
  schedule:
    - cron: '*/5 * * * *'
      
jobs:
  schedule_action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '2.x', '3.x', 'pypy2', 'pypy3' ]
    name: Python ${{ matrix.python-version }} sample
    steps:
      - name: Print python version
        run: python --version        
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: python ./src/builder.py
      
